kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  serviceName: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.7.19
          ports:
            - containerPort: 3306
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: host-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi



