apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis-master
  selector:
    app: redis-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-master
          image: redis:4.0.5
          command:
            - redis-server
          args:
            - /usr/local/etc/redis/redis-master.conf
          ports:
            - containerPort: 6379
              name: redis-server
          readinessProbe:
            exec:
              command: ['redis-cli','-a','123456', 'info', 'server']
          volumeMounts:
            - name: redis-master-volume
              mountPath: /data
            - name: redis-conf
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-conf
          configMap:
            name: redis-server-cm
            items:
              - key: redis-master.conf
                path: redis-master.conf
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-master
                        - redis-slave
                topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: redis-master-volume
        annotations:
          volume.beta.kubernetes.io/storage-class: "aliyun-nas"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
