apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  clusterIP: None
  ports:
  - port: 26379
    name: redis-sentinel
  selector:
    app: redis-sentinel
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: redis:4.0.5
          command:
            - redis-server
          args:
            - /usr/local/etc/redis/sentinel.conf
            - --sentinel
          ports:
            - containerPort: 26379
              name: redis-sentinel
          volumeMounts:
            - name: redis-sentinel-volume
              mountPath: /data
            - name: redis-conf
              mountPath: /usr/local/etc/redis
      volumes:
        - name: redis-sentinel-volume
        - name: redis-conf
          configMap:
            name: redis-server-cm
            items:
              - key: sentinel.conf
                path: sentinel.conf
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-sentinel
                topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: redis-sentinel-volume
        annotations:
          volume.beta.kubernetes.io/storage-class: "aliyun-nas"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
